-- =====================
-- NOCTRA SEO — Site Auditor Module
-- Migration: 20260405000000_create_audit_tables.sql
--
-- NOTE: This project has no "sites" table. The equivalent is "domains".
-- site_id from the spec → domain_id referencing domains(id).
--
-- This migration replaces the basic audit_jobs stub from 001_initial_schema.sql
-- with the full Site Auditor schema.
-- =====================

-- ----------------------
-- 1. DROP EXISTING STUB
-- ----------------------
-- Remove the policy and table created in 001_initial_schema.sql

drop policy if exists "org_isolation" on audit_jobs;
alter table if exists audit_jobs disable row level security;
drop table if exists audit_jobs cascade;

-- ----------------------
-- 2. audit_jobs
-- ----------------------
-- One row per audit execution on a domain.
-- domain_id maps to the spec's site_id (adapted to this project's schema).

create table audit_jobs (
  id              uuid      primary key default gen_random_uuid(),
  domain_id       uuid      not null references domains(id)     on delete cascade,
  user_id         uuid      not null references auth.users(id)  on delete cascade,

  status          text      not null default 'pending'
                            check (status in ('pending', 'running', 'completed', 'failed')),

  triggered_by    text      not null default 'manual'
                            check (triggered_by in ('manual', 'onboarding', 'scheduled')),

  started_at      timestamptz,
  completed_at    timestamptz,

  -- Aggregate scores (0–100, nullable until job completes)
  score_overall     int2,
  score_seo         int2,
  score_dns         int2,
  score_security    int2,
  score_performance int2,
  score_tech        int2,
  score_reputation  int2,

  created_at      timestamptz not null default now(),

  -- Score range constraints
  constraint chk_score_overall     check (score_overall     between 0 and 100),
  constraint chk_score_seo         check (score_seo         between 0 and 100),
  constraint chk_score_dns         check (score_dns         between 0 and 100),
  constraint chk_score_security    check (score_security    between 0 and 100),
  constraint chk_score_performance check (score_performance between 0 and 100),
  constraint chk_score_tech        check (score_tech        between 0 and 100),
  constraint chk_score_reputation  check (score_reputation  between 0 and 100)
);

-- ----------------------
-- 3. audit_checks
-- ----------------------
-- Individual check result within a job.

create table audit_checks (
  id              uuid      primary key default gen_random_uuid(),
  job_id          uuid      not null references audit_jobs(id) on delete cascade,

  check_key       text      not null,  -- e.g. 'ssl_chain', 'robots_txt', 'dns_records'
  "group"         text      not null
                            check ("group" in ('seo', 'dns', 'security', 'performance', 'tech', 'reputation')),

  status          text      not null
                            check (status in ('pass', 'warn', 'fail', 'info', 'error')),

  score           int2,                -- 0–100, nullable (not all checks have a numeric score)
  data            jsonb,               -- raw result from the check
  summary         text,                -- human-readable summary generated by Claude
  recommendations jsonb,               -- array of { priority: 'high'|'medium'|'low', action: string }

  created_at      timestamptz not null default now(),

  constraint chk_check_score check (score between 0 and 100)
);

-- ----------------------
-- 4. INDEXES
-- ----------------------

-- audit_jobs: list audit history per domain (most recent first)
create index idx_audit_jobs_domain_date
  on audit_jobs(domain_id, created_at desc);

-- audit_jobs: find active/pending jobs for a user
create index idx_audit_jobs_user_status
  on audit_jobs(user_id, status);

-- audit_checks: filter checks by group within a job
create index idx_audit_checks_job_group
  on audit_checks(job_id, "group");

-- audit_checks: enforce uniqueness of check_key per job
create unique index idx_audit_checks_job_key
  on audit_checks(job_id, check_key);

-- ----------------------
-- 5. RLS
-- ----------------------

alter table audit_jobs   enable row level security;
alter table audit_checks enable row level security;

-- audit_jobs: users can only see/write their own jobs
create policy "audit_jobs_select"
  on audit_jobs for select
  using (auth.uid() = user_id);

create policy "audit_jobs_insert"
  on audit_jobs for insert
  with check (auth.uid() = user_id);

create policy "audit_jobs_update"
  on audit_jobs for update
  using (auth.uid() = user_id);

-- audit_checks: access is gated through the parent job's user_id
create policy "audit_checks_select"
  on audit_checks for select
  using (
    exists (
      select 1
      from audit_jobs j
      where j.id = audit_checks.job_id
        and j.user_id = auth.uid()
    )
  );

create policy "audit_checks_insert"
  on audit_checks for insert
  with check (
    exists (
      select 1
      from audit_jobs j
      where j.id = audit_checks.job_id
        and j.user_id = auth.uid()
    )
  );

-- =====================
-- TypeScript types
-- (copy to types/audit.ts)
-- =====================
/*
// types/audit.ts

export type AuditStatus  = 'pending' | 'running' | 'completed' | 'failed'
export type CheckStatus  = 'pass' | 'warn' | 'fail' | 'info' | 'error'
export type CheckGroup   = 'seo' | 'dns' | 'security' | 'performance' | 'tech' | 'reputation'
export type TriggeredBy  = 'manual' | 'onboarding' | 'scheduled'

export interface CheckRecommendation {
  priority: 'high' | 'medium' | 'low'
  action: string
}

export interface AuditJob {
  id:                string
  domain_id:         string        // maps to spec's site_id — references domains(id)
  user_id:           string
  status:            AuditStatus
  triggered_by:      TriggeredBy
  started_at:        string | null
  completed_at:      string | null
  score_overall:     number | null  // 0–100
  score_seo:         number | null
  score_dns:         number | null
  score_security:    number | null
  score_performance: number | null
  score_tech:        number | null
  score_reputation:  number | null
  created_at:        string
}

export interface AuditCheck {
  id:              string
  job_id:          string
  check_key:       string          // e.g. 'ssl_chain', 'robots_txt', 'dns_records'
  group:           CheckGroup
  status:          CheckStatus
  score:           number | null   // 0–100, not all checks have a numeric score
  data:            Record<string, unknown> | null
  summary:         string | null
  recommendations: CheckRecommendation[] | null
  created_at:      string
}
*/
